export const glyphsImport = {
  DIO: "/glyphs/DIO.svg",
  FIIN: "/glyphs/FIIN.svg",
  FNO: "/glyphs/FNO.svg",
  GLO: "/glyphs/GLO.svg",
  KYO: "/glyphs/KYO.svg",
  NMA: "/glyphs/NMA.svg",
  ɲAI: "/glyphs/ɲAI.svg",
  PLAN: "/glyphs/PLAN.svg",
  SKAN: "/glyphs/SKAN.svg",
  TÈON: "/glyphs/TÈON.svg",
  TʁAN: "/glyphs/TʁAN.svg",
  ʇRI: "/glyphs/ʇRI.svg",
  VʁÉ: "/glyphs/VʁÉ.svg",
  WÈI: "/glyphs/WÈI.svg",
  XIO: "/glyphs/XIO.svg",
  ZBA: "/glyphs/ZBA.svg",
  ʗSO: "/glyphs/ʗSO.svg",
  THE_SCRIBE: "/glyphs/theScribe.svg",
};
