export const glyphsImport = {
  DIO: "/glyphs/DIO.svg",
  FIIN: "/glyphs/FIIN.svg",
  FNO: "/glyphs/FNO.svg",
  GLO: "/glyphs/GLO.svg",
  KRO: "/glyphs/KRO.svg",
  NMA: "/glyphs/NMA.svg",
  GNAI: "/glyphs/ɲAI.svg",
  PLAN: "/glyphs/PLAN.svg",
  SKAN: "/glyphs/SKAN.svg",
  YEON: "/glyphs/TÈON.svg",
  TRAN: "/glyphs/TʁAN.svg",
  TRI: "/glyphs/ʇRI.svg",
  VRE: "/glyphs/VʁÉ.svg",
  WEI: "/glyphs/WÈI.svg",
  XIO: "/glyphs/XIO.svg",
  ZBA: "/glyphs/ZBA.svg",
  CSO: "/glyphs/ʗSO.svg",
  THE_SCRIBE: "/glyphs/theScribe.svg",
};
